primary_colors:
  primary: "#D73809"
  secondary: "#60748D"
  tertiary: "#940C08"
  positive: "#09d738"
  negative: "#D73809"
  neutral: "#CFD6D5"

light_primary_colors:
  primary: "#f98f70"
  secondary: "#a3b0c0"
  tertiary: "#f87f7c"

color_list: 
  - "#D73809"
  - "#60748D"
  - "#940C08"
  - "#CA5E1B"
  - "#BD6A5F"
  - "#3D180F"
  - "#C2322D"
  - "#5C3431"
  - "#B79F9F"
  - "#CFD6D5"

divergent_colors:
  start: "#D73809"
  mid: "#c2c2c2"
  end: "#940C08"

sequential_colors:
  start: "#D73809"
  end: "#f98f70"

callout_colors:
  line_color: "#222222"
  text_color: "#000000"
  text_bg_color: "#ffffff"
  circle_line_color: "#D73809"

plot_colors:
  line_color: "#000000"
  text_color: "#000000"
  bg_color: "#ffffff"

custom_sequential:
  reds:
    - "#D73809"
    - "#f98f70"
  ice:
    - "#60748D"
    - "#a3b0c0"
  hot_cold:
    - "#D73809"
    - "#60748D"

custom_diverging:
  reds:
    - "#D73809"
    - "#c2c2c2"
    - "#940C08"
